name: chroma
channels:
  - conda-forge
dependencies:
  - python=3.13.2
  - nglview=3.1.4
  - pandas=2.2.3
  - pillow=11.1.0
  - pytest=8.3.5
  - scipy=1.15.2
  - pytorch=2.6.0
  - tqdm=4.67.1
  - tranformers=4.51.0
  - scikit_learn=1.6.1

